---
title: "Reporte"
author: "Carlos Crespín"
date: "2024-06-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rio)
data=import("TC_P-A_maran.xlsx")
```

```{r}
str(data)
```

# Edades de los participantes

```{r}
summary(data$edad)
```

```{r}
library(ggplot2)
library(ggthemes)
bpe=ggplot(data, aes(x = factor(1), y = edad)) + # x=factor(1) para agrupar todas las edades en un solo boxplot
  geom_boxplot() +                           # Crear el boxplot
  geom_hline(aes(yintercept = mean(edad)),   # Agregar la línea de la media
             color = "red", linetype = "dashed") +
  coord_flip() +                             # Hacer el boxplot horizontal
  labs(title = "Edades de participantes", 
       x = "", 
       y = "Edad") +                         # Título y etiquetas
  theme_test() +
  theme(legend.position = "none") +          # Quitar leyenda por defecto
  geom_text(aes(x = 1.3, y = mean(edad), label = "Media"), 
            color = "red", angle = 90, vjust = -0.5)  # Agregar texto de la media
bpe
```
```{r}
saveRDS(bpe, file = "bp_age.rds")

```


# Educación de los participantes

```{r}
conteo_estudia <- as.data.frame(table(data$e1))
names(conteo_estudia) <- c("Estudia", "Frecuencia")

pc1=ggplot(conteo_estudia, aes(x = "", y = Frecuencia, fill = Estudia)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar(theta = "y") +   # Convertir el gráfico de barras en un pie chart
  theme_void() +               # Quitar el fondo y los ejes
  labs(title = "Distribución de participantes que actualmente están estudiando") +
  theme(legend.title = element_blank())

pc1 <- pc1 + geom_text(aes(label = paste0(round((Frecuencia/sum(Frecuencia))*100, 1), "%")),
                                   position = position_stack(vjust = 0.5))

pc1+theme_classic2()
```
```{r}
saveRDS(pc1, file = "pc_e1.rds")

```


```{r}
conteo_nivel <- as.data.frame(table(data$e2))
names(conteo_nivel) <- c("Nivel", "Frecuencia")

pc2=ggplot(conteo_nivel, aes(x = "", y = Frecuencia, fill = Nivel)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar(theta = "y") +   # Convertir el gráfico de barras en un pie chart
  theme_minimal() +               # Quitar el fondo y los ejes
  labs(title = "Distribución de nivel educativo en curso") +
  theme(legend.title = element_blank())

pc2 <- pc2 + geom_text(aes(label = paste0(round((Frecuencia/sum(Frecuencia))*100, 1), "%")),
                                   position = position_stack(vjust = 0.5))

pc2+theme_classic2()
```
```{r}
saveRDS(pc2, file = "pc_e2.rds")

```


# ¿Con quiénes vivía el participante antes de ingresar al centro?

```{r}
conteo_fam1 <- as.data.frame(table(data$fam1))
names(conteo_fam1) <- c("Madre", "Frecuencia")

pc3=ggplot(conteo_fam1, aes(x = "", y = Frecuencia, fill = Madre)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar(theta = "y") +   # Convertir el gráfico de barras en un pie chart
  theme_minimal() +               # Quitar el fondo y los ejes
  labs(title = "¿Vive con su madre?") +
  theme(legend.title = element_blank())

pc3 <- pc3 + geom_text(aes(label = paste0(round((Frecuencia/sum(Frecuencia))*100, 1), "%")),
                                   position = position_stack(vjust = 0.5))

pc3+theme_minimal()
```
```{r}
saveRDS(pc3, file = "pc_fam1.rds")

```


```{r}
conteo_fam2 <- as.data.frame(table(data$fam2))
names(conteo_fam2) <- c("Padre", "Frecuencia")

pc4=ggplot(conteo_fam2, aes(x = "", y = Frecuencia, fill = Padre)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar(theta = "y") +   # Convertir el gráfico de barras en un pie chart
  theme_excel_new() +               # Quitar el fondo y los ejes
  labs(title = "¿Vive con su padre?") +
  theme(legend.title = element_blank())

pc4 <- pc4 + geom_text(aes(label = paste0(round((Frecuencia/sum(Frecuencia))*100, 1), "%")),
                                   position = position_stack(vjust = 0.5))

pc4+theme_classic2()
```
```{r}
saveRDS(pc4, file = "pc_fam2.rds")

```


```{r}
conteo_fam3 <- as.data.frame(table(data$fam3))
names(conteo_fam3) <- c("Hermanos", "Frecuencia")

pc5=ggplot(conteo_fam3, aes(x = "", y = Frecuencia, fill = Hermanos)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar(theta = "y") +   # Convertir el gráfico de barras en un pie chart
  theme_excel_new() +               # Quitar el fondo y los ejes
  labs(title = "¿Vive con sus hermanos?") +
  theme(legend.title = element_blank())

pc5 <- pc5 + geom_text(aes(label = paste0(round((Frecuencia/sum(Frecuencia))*100, 1), "%")),
                                   position = position_stack(vjust = 0.5))

print(pc5)
```
```{r}
saveRDS(pc5, file = "pc_fam3.rds")

```



```{r}
conteo_fam4 <- as.data.frame(table(data$fam4))
names(conteo_fam4) <- c("Otros", "Frecuencia")

pc6=ggplot(conteo_fam4, aes(x = "", y = Frecuencia, fill = Otros)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar(theta = "y") +   # Convertir el gráfico de barras en un pie chart
  theme_excel_new() +               # Quitar el fondo y los ejes
  labs(title = "¿Vive con algún otro familiar?") +
  theme(legend.title = element_blank())

pc6 <- pc6 + geom_text(aes(label = paste0(round((Frecuencia/sum(Frecuencia))*100, 1), "%")),
                                   position = position_stack(vjust = 0.5))

pc6+theme_classic2()
```
```{r}
saveRDS(pc6, file = "pc_fam4.rds")

```


# ¿Tiene hijos?

```{r}
install.packages("ggpubr")
library(ggpubr)

conteo_h1 <- as.data.frame(table(data$h1))
names(conteo_h1) <- c("Hijos", "Frecuencia")

# Crear el pie chart
pie_chart <- ggplot(conteo_h1, aes(x = "", y = Frecuencia, fill = Hijos)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y") +
  theme_minimal() +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid = element_blank(),
    axis.text.x = element_blank()
  ) +
  scale_fill_manual(values = c("#FF9999", "#66B2FF", "#99FF99")) + # Colores personalizados
  ggtitle("¿Tiene hijos?") +
  theme(plot.title = element_text(hjust = 0.5))

# Añadir etiquetas
pie_chart <- pie_chart + geom_text(aes(label = paste0(round((Frecuencia/sum(Frecuencia))*100, 1), "%")),
                                   position = position_stack(vjust = 0.5))

# Mostrar el gráfico
pie_chart+theme_tufte()
```
```{r}
saveRDS(pie_chart, file = "pc_h1.rds")

```


# Infracción por la que entró al centro

```{r}
conteo_inf <- as.data.frame(table(data$inf))
names(conteo_inf) <- c("Infraccion", "Frecuencia")
```

```{r}
install.packages("RColorBrewer")
```


```{r}
library(ggplot2)
library(RColorBrewer)
bar_chart <- ggplot(conteo_inf, aes(x = reorder(Infraccion, -Frecuencia), y = Frecuencia, fill = Infraccion)) +
  geom_bar(stat = "identity", width = 0.7) +
  theme_minimal() +
  labs(title = "Infracciones",
       x = "Infraccion",
       y = "Cantidad de menores") +
  theme(plot.title = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
        axis.text.y = element_text(size = 10),
        legend.position = "none") +
  scale_fill_brewer(palette = "Dark2")

# Mostrar el gráfico
print(bar_chart)
```
```{r}
saveRDS(bar_chart, file = "bar_inf.rds")
```


# Tiempo dentro y tiempo de sentencia

```{r}
# Transformar los datos a formato largo
library(tidyr)
internos_long <- data %>%
  pivot_longer(cols = c(t1, t2),
               names_to = "tipo",
               values_to = "meses")
library(dplyr)
medias <- internos_long %>%
  group_by(tipo) %>%
  summarize(media = mean(meses))

internos_long[internos_long$tipo=='t1','tipo']='Tiempo en el centro'
internos_long[internos_long$tipo=='t2','tipo']='Tiempo de sentencia'


boxplot <- ggplot(internos_long, aes(x = tipo, y = meses, fill = tipo)) +
  geom_boxplot() +
  geom_hline(data = medias, aes(yintercept = media, color = tipo), linetype = "dashed") +
  scale_fill_brewer(palette = "R3") +
  scale_color_manual(values = c("meses_en_penal" = "red", "tiempo_de_condena" = "blue")) +
  theme_minimal() +
  labs(title = "Tiempo dentro del Centro y Tiempo de Sentencia",
       x = "Tipo",
       y = "Meses",
       fill = "Tipo",
       color = "Media") +
  theme(plot.title = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10))

# Mostrar el gráfico
print(boxplot)
```
```{r}
saveRDS(boxplot, file = "bpT.rds")
```
























